In [23]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4', '5' ]
array_list = np.array(object = list_)

In [24]:
#1)
# The difference in the data type of variables list and array list is that the variable list has 'list' datatype whereas array list as 'numpy.ndarray' datatype. 
print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


In [25]:
#2)
print('The elements in the list_ are: ')
for i in range(len(list_)):
    print(list_[i],type(list_[i]))
print('The elements in the array_list are: ')
for i in range(len(array_list)):
    print(array_list[i], type(array_list[i]))

The elements in the list_ are: 
1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>
The elements in the array_list are: 
1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


In [26]:
array_list = np.array(object = list_, dtype = int)

In [27]:
#3)
# Yes the difference is the variable list_ will be having 'String' datatype whereas array_list will be having 'int' datatype.
print('The elements in the list_ are: ')
for i in range(len(list_)):
    print(list_[i],type(list_[i]))
print('The elements in the array_list are: ')
for i in range(len(array_list)):
    print(array_list[i], type(array_list[i]))

The elements in the list_ are: 
1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>
The elements in the array_list are: 
1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>
5 <class 'numpy.int64'>


In [28]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [33]:
#4)
#i)
print('The shape of the num_array is:',num_array.shape)
#ii)
print('The size of the num_array is:',num_array.size)

The shape of the num_array is: (2, 3)
The size of the num_array is: 6


In [43]:
#5)
ar_zeros=np.zeros((3,3))
print(ar_zeros)
print('The shape of the array is:',ar_zeros.shape)
print('The size of the array is:',ar_zeros.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
The shape of the array is: (3, 3)
The size of the array is: 9


In [45]:
#6)
iden=np.eye(5)
iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])